# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.100'
- task: UseNode@1
  inputs:
    version: '13.x'
    checkLatest: true
- script: | 
    cd src
    npm install
  displayName: 'npm install'
- script: | 
    cd src
    dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: | 
    cd src
    dotnet pack --configuration $(buildConfiguration) -o bin/dist
  displayName: 'dotnet pack $(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'src/bin/dist'
    Contents: '**.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'BlazorScrollView'
    publishLocation: 'Container'